#############
#############
# INSERT DATA
#############
#############

#############
# entities  #
#############

#persons
insert $x isa person, has name "Lise Thorvaldsen";
insert $x isa person, has name "Kirsten Hansen";
insert $x isa person, has name "Boris Thomsen";
insert $x isa person, has name "Sarah Bentsen";
insert $x isa person, has name "Andreas Tollsteen";
insert $x isa person, has name "Mufti Shill";
insert $x isa person, has name "Hodja de Piort";
insert $x isa person, has name "Beatrice Umlow";
insert $x isa organisation, has name "Bali Grim Ltd";
insert $x isa corporation, has name "Alm. Udnytteboliger A/S";

# property
insert $x isa house, has address "Joergensvej 2";
insert $x isa house, has address "Joergensvej 4";
insert $x isa house, has address "Mogensvej 110";
insert $x isa house, has address "Mogensvej 112";


#############
# relations #
#############

# tenancies
match $house isa house, has address "Joergensvej 2"; $tenant1 isa person, has name "Kirsten Hansen"; $tenant2 isa person, has name "Boris Thomsen"; $landlord isa person, has name "Lise Thorvaldsen"; insert (tenant: $tenant1, tenant: $tenant2, landlord: $landlord, rented-property:$house) isa tenancy, has starting-date "2020-01-01";
match $house isa house, has address "Joergensvej 4"; $tenant isa person, has name "Sarah Bentsen"; $landlord isa person, has name "Mufti Shill"; insert (tenant: $tenant, landlord: $landlord, rented-property:$house) isa tenancy, has starting-date "2020-02-02";
match $house isa house, has address "Mogensvej 110"; $tenant isa person, has name "Beatrice Umlow"; $landlord isa corporation, has name "Alm. Udnytteboliger A/S"; insert (tenant: $tenant, landlord: $landlord, rented-property:$house) isa tenancy, has starting-date "2018-11-01";
match $house isa house, has address  "Mogensvej 112"; $tenant1 isa organisation, has name "Bali Grim Ltd"; $landlord isa person, has name "Andreas Tollsteen"; insert (tenant:$tenant1, landlord:$landlord, rented-property:$house) isa tenancy, has starting-date "2019-05-01";

# subtenancies
match $subtenant1 isa person, has name "Hodja de Piort"; $tenancy (tenant:$tenant1, landlord:$landlord, rented-property:$rented) isa tenancy; $tenant1 has name "Bali Grim Ltd"; $landlord  has name "Andreas Tollsteen"; insert $subtenancy (sublandlord:$tenant1, subtenant:$subtenant1, main-tenancy:$tenancy) isa subtenancy, has starting-date "2020-09-01";

# neighbourship
match $tenant1 isa person, has name "Kirsten Hansen"; $tenant2 isa person, has name "Sarah Bentsen"; insert (is-neighbour:$tenant1, is-neighbour:$tenant2) isa neighbourship;
match $tenant1 isa person, has name "Beatrice Umlow"; $tenant2 isa person, has name "Bali Grim Ltd"; insert (is-neighbour:$tenant1, is-neighbour:$tenant2) isa neighbourship;

# tenancy-dispute
match $tenant isa person, has name "Sarah Bentsen"; $landlord isa person, has name "Mufti Shill"; $tenancy (tenant:$tenant, landlord:$landlord) isa tenancy; insert (disputing-tenant: $tenant, disputing-landlord: $landlord, disputed-tenancy: $tenancy) isa tenancy-dispute, has starting-date "2020-05-15";
